app/assets/javascripts/components/rooms.js.jsx
app/assets/javascripts/rooms.coffee
app/controllers/rooms_controller.rb
app/models/room.rb
app/views/rooms/show.html.erb
config/routes.rb

This allows user to stay the state after refreshing page.

Allow to set room status

---

app/assets/javascripts/components/rooms.js.jsx
app/controllers/application_controller.rb
app/controllers/rooms_controller.rb
app/helpers/application_helper.rb
app/helpers/rooms_helper.rb
app/models/room.rb
app/views/rooms/_monitor.html.erb
app/views/rooms/show.html.erb

This is because I set `story_id` from cookie, which leads to it shares across rooms, which leads to showing wrong points when user vote across multi rooms. 
Solution is to calculate current story from backend.

Fix wrong story point across rooms

---

app/assets/javascripts/components/rooms.js.jsx
app/assets/stylesheets/rooms.scss
app/controllers/rooms_controller.rb
app/models/user.rb
app/views/rooms/user_list.json.jbuilder

Fix https://github.com/hlcfan/pokr/issues/25
If user voted, there will be a blue bar next to his avatar

Show users who voted

---

app/assets/javascripts/components/action_box.js.jsx
app/models/room.rb

The way now is kinda dumb, gotta find a better way.

Show decide point tip

---

app/models/user.rb
app/models/user_story_point.rb
spec/models/story_spec.rb
spec/models/user_room_spec.rb
spec/models/user_spec.rb
spec/models/user_story_point_spec.rb

Tests without FactoryGirl looking good!

Tests for models

---

spec/controllers/home_controller_spec.rb

For https://github.com/hlcfan/pokr/issues/35

Tests for HomeController

---

spec/controllers/profile_controller_spec.rb

For https://github.com/hlcfan/pokr/issues/35

Tests for ProfileController

---

app/assets/javascripts/application.js
app/assets/javascripts/components/action_box.js.jsx
app/assets/javascripts/components/people_list_box.js.jsx
app/assets/javascripts/components/point_bar.js.jsx
app/assets/javascripts/components/result_panel.js.jsx
app/assets/javascripts/components/shared.js.jsx
app/assets/javascripts/components/story_list_box.js.jsx
app/assets/javascripts/components/vote_box.js.jsx
app/assets/javascripts/home.coffee
app/assets/javascripts/rooms.coffee
app/channels/application_cable/connection.rb
app/channels/rooms_channel.rb
app/controllers/application_controller.rb
app/controllers/rooms_controller.rb
app/views/rooms/show.html.erb
config/initializers/assets.rb

+ Switch from HTTP to WS
+ Simplify Events used to communicate across components.

Switch from HTTP to WS

---

app/assets/javascripts/components/point_bar.js.jsx
app/assets/javascripts/components/result_panel.js.jsx
app/assets/javascripts/components/shared.js.jsx

To resolve https://github.com/hlcfan/pokr/issues/57

Colorize point bar

---

app/assets/javascripts/components/board.js.jsx
app/assets/javascripts/components/point_bar.js.jsx
app/assets/javascripts/components/shared.js.jsx
app/assets/javascripts/components/vote_box.js.jsx

Simply add a mapping to show point as emojis.

Show emoji for some of the points

---

CHANGELOG.md
app/assets/javascripts/components/action_box.js.jsx
app/assets/javascripts/components/shared.js.jsx
app/assets/stylesheets/rooms.scss
app/controllers/rooms_controller.rb
app/models/room.rb
app/views/rooms/_form.html.erb
app/views/rooms/show.html.erb
db/migrate/20161009083502_add_timer_to_rooms.rb
db/schema.rb
spec/controllers/rooms_controller_spec.rb
spec/models/room_spec.rb

https://github.com/hlcfan/pokr/issues/53

Add egg timer

---

CHANGELOG.md
app/assets/javascripts/components/shared.js.jsx
app/assets/javascripts/components/story.js.jsx
app/assets/javascripts/components/story_list.js.jsx
app/assets/javascripts/components/story_list_box.js.jsx
app/assets/stylesheets/rooms.scss
app/channels/rooms_channel.rb
app/controllers/rooms_controller.rb
app/models/room.rb
app/views/rooms/story_list.json.jbuilder
spec/controllers/rooms_controller_spec.rb
spec/models/room_spec.rb

Existing issue
+ Cannot re-vote the last story
Fix https://github.com/hlcfan/pokr/issues/66

More interactions to story list

---

CHANGELOG.md
app/models/story.rb
app/presenters/user_presenter.rb
app/views/dashboard/index.html.erb
spec/presenters/user_presenter_spec.rb

+ Add skip rate to stats
+ Fix bugs for blank dashboard(new user)

Add skip rate to stats

---

app/assets/javascripts/feedback.js
app/controllers/home_controller.rb
app/views/home/index.html.erb
app/views/home/sign_up_form.html.erb
config/routes.rb
spec/controllers/home_controller_spec.rb

Turns out the form token is cached.

Fix landing page sign up error

---

app/assets/javascripts/application.js
app/assets/javascripts/components/action_box.js.jsx
app/assets/javascripts/components/room.js.jsx
app/assets/javascripts/components/shared.js.jsx
app/assets/javascripts/components/status_bar.js.jsx
app/assets/javascripts/components/story_list_box.js.jsx
app/assets/javascripts/components/vote_box.js.jsx
app/assets/javascripts/page_init.coffee
app/assets/javascripts/room_init.coffee
app/assets/javascripts/rooms.coffee
app/assets/stylesheets/rooms.scss
app/mailers/application_mailer.rb
app/models/room.rb
app/views/rooms/show.html.erb
spec/models/room_spec.rb

Allow modify room

---

app/assets/javascripts/application.js
app/assets/javascripts/common.js
app/assets/javascripts/components/board.js.jsx
app/assets/javascripts/components/story.js.jsx
app/assets/stylesheets/rooms.scss

Cleaner result panel

---

app/assets/javascripts/rooms.coffee
app/assets/stylesheets/rooms.scss
app/views/rooms/_form.html.erb

Keep room form intact

---

app/assets/javascripts/components/status_bar.js.jsx
app/assets/stylesheets/rooms.scss
app/models/user.rb
spec/models/user_spec.rb

Moderator:
Participant/Watcher:
+ Add share button
+ Add emojis for buttons
+ Confirm before change room status

Add share button

---

app/assets/javascripts/components/action_box.js.jsx
app/assets/javascripts/components/shared.js.jsx
app/channels/rooms_channel.rb

Allow clear votes

---

client/app/bundles/Room/components/ActionBox.jsx
client/app/bundles/Room/components/PeopleListBox.jsx
client/app/bundles/Room/components/VoteBox.jsx
client/app/bundles/Room/containers/Room.jsx
client/app/libs/actionCable.js
client/app/libs/roomActions.js

+ Fix timer
+ Fix close room button

Fix misc parts

---

app/assets/javascripts/page_init.coffee
app/assets/javascripts/room_init.coffee
client/app/bundles/Room/components/ActionBox.jsx
client/app/bundles/Room/components/Story.jsx
client/app/bundles/Room/components/StoryList.jsx
client/app/bundles/Room/components/StoryListBox.jsx
client/app/bundles/Room/containers/Room.jsx

My bad, wan't have all the POKER vars removed, removing now.
Following of https://github.com/hlcfan/pokr/pull/106

Eliminate POKER var

---

app/helpers/application_helper.rb
app/views/home/sign_up_form.html.erb

Render shared links

---

client/app/bundles/Room/components/ActionBox/ActionBox.jsx
client/app/bundles/Room/components/ActionBox/ResultPanel/ResultPanel.jsx
client/app/bundles/Room/components/PeopleListBox.jsx
client/app/libs/actionCable.js
client/app/libs/roomActions.js
client/package.json
client/yarn.lock

Consensus animation

---

.travis.yml
client/package.json
client/webpack.config.dev.js
client/webpack.config.prod.js
client/yarn.lock
config/initializers/react_on_rails.rb

Configure webpack

---

Gemfile
Gemfile.lock
app/models/user.rb
config/routes.rb

Add logster

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/home/index.html.erb
app/views/layouts/_footer.html.erb
config/locale.rb
config/locales/en.yml
config/locales/zh-CN.yml
config/locales/zh_cn.yml

As Agile development method is being popular in China,
it's better to support Chinese for Baidu to crawl it.

Add i18n for landing page

---

app/models/room.rb
spec/controllers/rooms_controller_spec.rb
spec/models/room_spec.rb

Optimize SQL while getting user list

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/locales/zh-CN.yml

Mate from Spain said Pokrex raises errors from his laptop.
It's because I'm using less robust way to detect user lang, correcting now.
Who knows how many foreign users get way while seeing errors, aww.

Fix user browser language detection

---

Gemfile
Gemfile.lock
app/assets/javascripts/rooms.coffee
app/assets/stylesheets/rooms.scss
app/controllers/application_controller.rb
app/controllers/rooms_controller.rb
app/helpers/rooms_helper.rb
app/models/room.rb
app/repositories/room_repository.rb
app/views/rooms/_form.html.erb
app/views/rooms/_point_values.html.erb
client/app/libs/barColors.js
client/package.json
client/webpack.config.dev.js
client/yarn.lock
config/webpacker.yml
db/migrate/20170923125354_add_scheme_to_rooms.rb
db/schema.rb
package.json
spec/controllers/rooms_controller_spec.rb
spec/helpers/rooms_helper_spec.rb
spec/models/room_spec.rb

Support multi point schemes

---

Procfile.dev
config/database.yml.template
db/schema.rb
package.json

Fixes for a couple of issues I ran into while trying to run pokrex locally.

Fix typo in database config template; fix build command; update schema

---

app/views/site/about.en.html.erb
config/locales/en.yml

Some language fixes and improvements on the home and about pages.

Language fixes and improvements on home and about pages

---

app/views/dashboard/index.html.erb
app/views/layouts/_nav.html.erb
app/views/rooms/_form.html.erb
app/views/rooms/_story_form.html.erb
app/views/rooms/new.html.erb
app/views/site/faq.en.html.erb
client/app/bundles/Room/components/ActionBox/ActionBox.jsx
client/app/bundles/Room/components/PeopleListBox.jsx
client/app/bundles/Room/components/StatusBar.jsx
client/app/bundles/Room/components/StoryListBox.jsx
client/app/bundles/Room/components/VoteBox.jsx

Language fixes and improvements on the FAQ, Room, and Dashboard pages.

Language fixes

---

app/channels/rooms_channel.rb
app/controllers/rooms_controller.rb
client/app/bundles/Room/components/TimeCounter.jsx
client/app/bundles/Room/containers/Room.jsx
spec/controllers/rooms_controller_spec.rb

Timejs temp patch

---

Gemfile
Gemfile.lock
app/views/room_invitation_mailer/invite.html.erb
config/environments/development.rb

So that user can directly scan QR code to join room.

Show QR code in invitation mail

---

.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/dashboard.coffee
app/assets/javascripts/typeahead.coffee
app/assets/stylesheets/application.css
app/assets/stylesheets/fontawesome-ext.scss
app/assets/stylesheets/nav.scss
app/assets/stylesheets/typeahead.scss
app/controllers/typeahead_controller.rb
app/models/room.rb
app/models/story.rb
app/views/layouts/_nav.html.erb
config/initializers/pg_search.rb
config/routes.rb
db/migrate/20180301050252_create_pg_search_documents.rb
db/schema.rb
spec/controllers/typeahead_controller_spec.rb
spec/models/room_spec.rb
spec/models/story_spec.rb

Revert "Revert "Support quick ticket/room search""

---

app/assets/stylesheets/site.scss
app/controllers/posts_controller.rb
app/models/post.rb
app/views/dashboard/_room_item.html.erb
app/views/dashboard/_story_item.html.erb
app/views/home/index.html.erb
app/views/layouts/_disqus.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb
app/views/layouts/post.html.erb
app/views/posts/index.html.erb
app/views/posts/pages/grooming-session-is-important.html.erb
config/locales/en.yml
config/locales/zh-CN.yml
config/routes.rb
spec/controllers/posts_controller_spec.rb
spec/fixtures/post.html.erb
spec/models/post_spec.rb

+ Post listing page 
+ Posts link at bottom
+ Add footer to most of the pages, except room related pages
+ Fix i18n issue, damn

Posts pages

---

app/assets/stylesheets/rooms.scss
app/channels/rooms_channel.rb
app/views/rooms/show.html.erb
client/app/bundles/Room/components/Invitation/index.scss
client/app/bundles/Room/components/PeopleList.jsx
client/app/bundles/Room/components/PeopleListBox.jsx
client/app/bundles/Room/components/Person.jsx
client/app/bundles/Room/containers/Room.jsx
client/app/bundles/Room/containers/RoomMobile.jsx
client/app/libs/airTraffic.js

Fix https://github.com/hlcfan/pokr/issues/186
+ Consider redux to manage app state instead of passing props down the way
+ HOC Room component

Allow moderator to kick people out

---

app/assets/stylesheets/dashboard.scss
app/views/dashboard/index.html.erb

Revert "Add ads to right side"

---

client/app/bundles/Room/components/Board.jsx

Show total point in board

---

app/assets/stylesheets/rooms.scss
client/app/bundles/Room/components/ActionBox/ActionBox.jsx

Tweak action panel to supress enticement of Skip/Clear buttons

---

app/assets/stylesheets/home.scss
app/views/layouts/_footer.html.erb
app/views/site/apps.html.erb
client/app/bundles/Room/components/Board.jsx
client/app/bundles/Room/components/StoryListBox/desktop.jsx
client/app/bundles/Room/components/Synk/index.jsx
client/app/bundles/Room/containers/Room.jsx
config/locales/en.yml
config/locales/zh-CN.yml
config/sitemap.rb
public/apps/Pokrex Setup 1.0.0.exe
public/apps/Pokrex-1.0.0.dmg
public/apps/Pokrex_1.0.0_amd64.deb
spec/views/rooms/show.html.erb_spec.rb

TODO:
+ [x] Link in board panel
+ [x] Default story point field
+ [x] Only moderator can sync issue
+ [ ] In browser, show synk link but show modal that asks users to install desktop app

Publicize apps page

---

.travis.yml
app/controllers/rooms_controller.rb
spec/controllers/rooms_controller_spec.rb

Fix issue that if only 10 participants, it fails to allow existing users to join. Darn.

Fix issue that if only 10 participants, it fails to allow existing users

---

app/assets/images/check.svg
app/assets/stylesheets/home.scss
app/assets/stylesheets/site.scss
app/controllers/site_controller.rb
app/views/home/index.html.erb
app/views/layouts/_footer.html.erb
app/views/site/pricing_page.html.erb
config/locales/en.yml
config/locales/zh-CN.yml
config/routes.rb
config/sitemap.rb
spec/controllers/site_controller_spec.rb

Pricing page

---

app/assets/stylesheets/rooms.scss
app/controllers/api/v1/schemes_controller.rb
app/models/room.rb
app/models/scheme.rb
app/views/rooms/_form.html.erb
app/views/rooms/_point_values.html.erb
app/views/rooms/_story_form.html.erb
spec/controllers/api/v1/schemes_controller_spec.rb
spec/models/room_spec.rb
spec/models/scheme_spec.rb

+ Add required field indication
+ Fix custom point schemes

New room page enhancement

---

app/models/scheme.rb
client/app/libs/barColors.js
spec/helpers/rooms_helper_spec.rb
spec/models/room_spec.rb
spec/models/scheme_spec.rb
spec/models/user_story_point_spec.rb

Correct fibonacci sequence 20 => 21

---

app/controllers/rooms_controller.rb
app/views/rooms/show.html.erb
client/app/libs/airTraffic.js
client/package.json
client/yarn.lock
spec/controllers/rooms_controller_spec.rb

Remove ActionCable js file

---

app/controllers/rooms_controller.rb
app/views/rooms/show.html.erb
client/app/libs/airTraffic.js
client/package.json
client/yarn.lock
spec/controllers/rooms_controller_spec.rb

Revert "Remove ActionCable js file"

---

app/assets/javascripts/application.js
app/assets/javascripts/billing.coffee
app/helpers/billing_helper.rb
app/models/subscription.rb
app/views/billing/show.html.erb
spec/helpers/billing_helper_spec.rb
spec/models/subscription_spec.rb

Better billing options
